apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
<<<<<<< HEAD
        image: 992382667448.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
=======
        image: 407622020962.dkr.ecr.us-east-1.amazonaws.com/frontend:1
>>>>>>> 68178dddb60ca3e06390335c4c0a45116b71132d
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://backend.mesdle.shop/api/tasks"
        ports:
        - containerPort: 3000